name: CI Production

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm install
    - run: npm run build
    - uses: JS-DevTools/npm-publish@v1
      name: NPM Publish
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
